# Generated by Django 5.2.6 on 2025-09-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='familyuseraccomplishment',
            name='accomplishment_id',
        ),
        migrations.RemoveField(
            model_name='familyuseraccomplishment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='familyuseraccomplishment',
            name='family_user_id',
        ),
        migrations.DeleteModel(
            name='MeasurementType',
        ),
        migrations.DeleteModel(
            name='AccomplishmentType',
        ),
        migrations.DeleteModel(
            name='Accomplishment',
        ),
        migrations.DeleteModel(
            name='FamilyUserAccomplishment',
        ),
    ]
