# Generated by Django 5.2.6 on 2025-09-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_accomplishment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '  User', 'verbose_name_plural': '  Users'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='familyuser',
            options={'verbose_name': 'Family User', 'verbose_name_plural': 'Family Users'},
        ),
    ]
