# Generated by Django 5.2.6 on 2025-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lang_code',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
