# Generated by Django 5.2.6 on 2025-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cursor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='', max_length=3),
        ),
    ]
