# Generated by Django 5.2.6 on 2025-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_first_name_alter_customuser_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='', max_length=3),
        ),
    ]
