# Generated by Django 5.2.6 on 2025-10-02 20:26

import core.utils.custom_user_defaults
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(default=core.utils.custom_user_defaults.get_first_custom_user, on_delete=django.db.models.deletion.CASCADE, related_name='family_createdcustom_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familyuser',
            name='custom_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_family_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyuser',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_family_users', to='core.family'),
        ),
    ]
