# Generated by Django 5.2.6 on 2025-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_family_created_by_familyuser_is_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statusses',
            },
        ),
    ]
