# Generated by Django 5.2.6 on 2025-10-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user',
            new_name='custom_user_id',
        ),
    ]
