# Generated by Django 5.2.6 on 2025-10-08 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_created_at_passwordreset_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInvite',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_invites', to='core.family')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_generated_family_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Invite',
                'verbose_name_plural': 'Family Invites',
            },
        ),
    ]
