# Generated by Django 5.2.6 on 2025-10-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_familyinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvite',
            name='family_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='family_invites', to='core.family'),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='generated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_generated_family_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='token',
            field=models.CharField(default='BxGaTylQ9qA3kimIF6KNph7fG96onTYzSjU679Ubiyx3OghJnSptLrHmv9vtxyLDAQXKy5qoHaSPD8NZKy6XpU9WogqbOhSQEI7i', editable=False, max_length=1000),
        ),
    ]
