# Generated by Django 5.2.6 on 2025-10-12 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_familyinvite_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvite',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_invites', to='core.family'),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_generated_family_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='token',
            field=models.CharField(default='nmTesNt9MPSRB1NC7NAPm78szbFtZiFFHVftucuM', max_length=1000, unique=True),
        ),
    ]
