# Generated by Django 5.2.6 on 2025-10-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_familyinvite_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvite',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
