# Generated by Django 5.2.6 on 2025-10-13 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_familyinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
