# Generated by Django 5.2.6 on 2025-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_familyuser_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyuser',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
