# Generated by Django 5.2.6 on 2025-10-08 13:39

import core.utils.custom_user_defaults
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accomplishment', '0004_alter_familyuseraccomplishment_measurement_quantity'),
        ('core', '0011_rename_created_at_passwordreset_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('frequency', models.CharField(max_length=100)),
                ('accomplishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_chores', to='accomplishment.accomplishment')),
                ('created_by', models.ForeignKey(default=core.utils.custom_user_defaults.get_first_custom_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_chores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chore',
                'verbose_name_plural': 'Chores',
            },
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('due_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user_chores_assigned_to_others', to='core.familyuser')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user_chores_to_do', to='core.familyuser')),
                ('chore_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_assignments', to='chore.chore')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_chore_assignments', to='core.status')),
            ],
            options={
                'verbose_name': 'Chore Assignment',
                'verbose_name_plural': 'Chore Assignments',
            },
        ),
    ]
