# Generated by Django 5.2.6 on 2025-10-07 14:22

import core.utils.custom_user_defaults
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Business Entity',
                'verbose_name_plural': 'Business Entities',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('symbol', models.CharField(max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerates_from', to='finance.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerates_to', to='finance.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
            ],
            options={
                'verbose_name': 'Import Profile',
                'verbose_name_plural': 'Import Profiles',
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completion_datetime', models.DateTimeField(null=True)),
                ('import_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.importprofile')),
            ],
            options={
                'verbose_name': 'Import History',
                'verbose_name_plural': 'Import Histories',
            },
        ),
        migrations.CreateModel(
            name='ImportProfileMapping',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('from_file_header', models.CharField(max_length=200)),
                ('to_transaction_header', models.CharField(max_length=200)),
                ('import_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.importprofile')),
            ],
            options={
                'verbose_name': 'Import Profile Mapping',
                'verbose_name_plural': 'Import Profile Mappings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created', models.DateTimeField()),
                ('transaction_date', models.DateTimeField()),
                ('reference', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('business_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_entity_transactions', to='finance.businessentity')),
                ('created_by', models.ForeignKey(default=core.utils.custom_user_defaults.get_first_custom_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_transactions', to='finance.currency')),
                ('import_history_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to='finance.importhistory')),
                ('transaction_category_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.transactioncategory')),
            ],
            options={
                'verbose_name': ' Transaction',
                'verbose_name_plural': ' Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionPattern',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name_regex', models.CharField(max_length=1000)),
                ('description_regex', models.CharField(max_length=1000)),
                ('reference_regex', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
            },
        ),
    ]
