# Generated by Django 5.2.6 on 2025-10-02 20:26

import core.utils.custom_user_defaults
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(default=core.utils.custom_user_defaults.get_first_custom_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerates_from', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangerates_to', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='business_entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_entity_transactions', to='finance.businessentity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_transactions', to='finance.currency'),
        ),
    ]
