# Generated by Django 5.2.6 on 2025-10-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_status'),
        ('finance', '0002_currency_symbol_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completion_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Import History',
                'verbose_name_plural': 'Import Histories',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='import_history_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to='finance.importhistory'),
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
            ],
            options={
                'verbose_name': 'Import Profile',
                'verbose_name_plural': 'Import Profiles',
            },
        ),
        migrations.AddField(
            model_name='importhistory',
            name='import_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.importprofile'),
        ),
        migrations.CreateModel(
            name='ImportProfileMapping',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('from_file_header', models.CharField(max_length=200)),
                ('to_transaction_header', models.CharField(max_length=200)),
                ('import_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.importprofile')),
            ],
            options={
                'verbose_name': 'Import Profile Mapping',
                'verbose_name_plural': 'Import Profile Mappings',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_category_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.transactioncategory'),
        ),
        migrations.CreateModel(
            name='TransactionPattern',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name_regex', models.CharField(max_length=1000)),
                ('description_regex', models.CharField(max_length=1000)),
                ('reference_regex', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
            },
        ),
    ]
