# Generated by Django 5.2.6 on 2025-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_importhistory_transactioncategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprofile',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
