# Generated by Django 5.2.6 on 2025-10-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_importprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
