# Generated by Django 5.2.6 on 2025-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_familyuser_deactivated'),
        ('finance', '0007_alter_transaction_created'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessentity',
            constraint=models.UniqueConstraint(fields=('name', 'family_id'), name='unique_business_entity_per_family'),
        ),
        migrations.AddConstraint(
            model_name='importprofile',
            constraint=models.UniqueConstraint(fields=('name', 'family_id'), name='unique_import_profile_per_family'),
        ),
    ]
