# Generated by Django 5.2.6 on 2025-10-19 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_familyuser_deactivated'),
        ('finance', '0008_businessentity_unique_business_entity_per_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='family_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AddConstraint(
            model_name='transactioncategory',
            constraint=models.UniqueConstraint(fields=('name', 'family_id'), name='unique_transaction_category_per_family'),
        ),
    ]
