# Generated by Django 5.2.6 on 2025-10-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transactioncategory_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
