# Generated by Django 5.2.6 on 2025-10-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_transactioncategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpattern',
            name='transaction_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_patterns', to='finance.transactioncategory'),
        ),
    ]
