# Generated by Django 5.2.6 on 2025-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_transactionpattern_transaction_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpattern',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='description_regex',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='name_regex',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='reference_regex',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
