# Generated by Django 5.2.6 on 2025-10-26 22:47

import django.db.models.deletion
import finance.models.transaction_category
import finance.models.transaction_pattern
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_familyuser_deactivated'),
        ('finance', '0012_alter_transactionpattern_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpattern',
            old_name='description_regex',
            new_name='business_entity_name',
        ),
        migrations.RemoveField(
            model_name='transactionpattern',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transactionpattern',
            name='name_regex',
        ),
        migrations.RemoveField(
            model_name='transactionpattern',
            name='reference_regex',
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='family_id',
            field=models.ForeignKey(default=finance.models.transaction_pattern.get_first_family, on_delete=django.db.models.deletion.CASCADE, related_name='family_transaction_patterns', to='core.family'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='family_id',
            field=models.ForeignKey(default=finance.models.transaction_category.get_first_family, on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='transaction_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_patterns_of_category', to='finance.transactioncategory'),
        ),
    ]
