# Generated by Django 5.2.6 on 2025-10-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_familyuser_deactivated'),
        ('finance', '0013_rename_description_regex_transactionpattern_business_entity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='family_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='family_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='family_transaction_patterns', to='core.family'),
        ),
    ]
