# Generated by Django 5.2.6 on 2025-10-11 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_calendar_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Entry',
                'verbose_name_plural': 'Calendar Entries',
            },
        ),
    ]
