# Generated by Django 5.2.6 on 2025-10-12 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_familyinvite'),
        ('ft_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_calendar_entries', to='core.family'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
