# Generated by Django 5.2.6 on 2025-09-24 18:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Accomplishment Type',
                'verbose_name_plural': 'Accomplishment Types',
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('abbreviation', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Measurement Type',
                'verbose_name_plural': 'Measurement Types',
            },
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('icon', models.CharField(blank=True, default='', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accomplishment_type', to='accomplishment.accomplishmenttype')),
                ('measurement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_type', to='accomplishment.measurementtype')),
            ],
            options={
                'verbose_name': '  Accomplishment',
                'verbose_name_plural': '  Accomplishments',
            },
        ),
        migrations.CreateModel(
            name='FamilyUserAccomplishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_quantity', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('accomplishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_id', to='accomplishment.accomplishment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_id', to=settings.AUTH_USER_MODEL)),
                ('family_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user', to='core.familyuser')),
            ],
            options={
                'verbose_name': ' Family User Accomplishment',
                'verbose_name_plural': ' Family User Accomplishments',
            },
        ),
    ]
    