# Generated by Django 5.2.6 on 2025-10-02 11:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('icon', models.CharField(blank=True, default='', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '  Accomplishment',
                'verbose_name_plural': '  Accomplishments',
            },
        ),
        migrations.CreateModel(
            name='AccomplishmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Accomplishment Type',
                'verbose_name_plural': 'Accomplishment Types',
            },
        ),
        migrations.CreateModel(
            name='FamilyUserAccomplishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_quantity', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': ' Family User Accomplishment',
                'verbose_name_plural': ' Family User Accomplishments',
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('abbreviation', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Measurement Type',
                'verbose_name_plural': 'Measurement Types',
            },
        ),
    ]
