# Generated by Django 5.2.6 on 2025-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]