# Generated by Django 5.2.6 on 2025-10-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accomplishment', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accomplishment_type', to='accomplishment.accomplishmenttype'),
        ),
        migrations.AddField(
            model_name='familyuseraccomplishment',
            name='accomplishment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_id', to='accomplishment.accomplishment'),
        ),
        migrations.AddField(
            model_name='familyuseraccomplishment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyuseraccomplishment',
            name='family_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user', to='core.familyuser'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='measurement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_type', to='accomplishment.measurementtype'),
        ),
    ]
