# Generated by Django 5.2.6 on 2025-09-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'verbose_name': '  Accomplishment', 'verbose_name_plural': '  Accomplishments'},
        ),
        migrations.AlterModelOptions(
            name='accomplishmenttype',
            options={'verbose_name': 'Accomplishment Type', 'verbose_name_plural': 'Accomplishment Types'},
        ),
        migrations.AlterModelOptions(
            name='familyuseraccomplishment',
            options={'verbose_name': ' Family User Accomplishment', 'verbose_name_plural': ' Family User Accomplishments'},
        ),
        migrations.AlterModelOptions(
            name='measurementtype',
            options={'verbose_name': 'Measurement Type', 'verbose_name_plural': 'Measurement Types'},
        ),
    ]
