# Generated by Django 5.2.6 on 2025-10-02 20:26

import core.utils.custom_user_defaults
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0002_alter_accomplishment_id'),
        ('core', '0008_family_created_by_familyuser_is_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='type',
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='accomplishment_type_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accomplishments', to='accomplishment.accomplishmenttype'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='is_achievement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='measurement_type_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='accomplishment.measurementtype'),
        ),
        migrations.AddField(
            model_name='familyuseraccomplishment',
            name='chore_assignment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chore_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='created_by',
            field=models.ForeignKey(default=core.utils.custom_user_defaults.get_first_custom_user, on_delete=django.db.models.deletion.PROTECT, related_name='custom_user_created_accomplishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='accomplishment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user_accomplishments', to='accomplishment.accomplishment'),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_family_user_accomplishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='family_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='core.familyuser'),
        ),
    ]
