# Generated by Django 5.2.6 on 2025-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0003_remove_accomplishment_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='measurement_quantity',
            field=models.BigIntegerField(null=True),
        ),
    ]
