# Generated by Django 5.2.6 on 2025-10-09 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0004_alter_familyuseraccomplishment_measurement_quantity'),
        ('core', '0012_familyinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='accomplishment_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_user_accomplishments', to='accomplishment.accomplishment'),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='chore_assignment_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chore_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_family_user_accomplishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='family_user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='core.familyuser'),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='measurement_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='familyuseraccomplishment',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
