# Generated by Django 5.2.6 on 2025-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0005_alter_familyuseraccomplishment_accomplishment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
