# Generated by Django 5.2.6 on 2025-10-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0006_alter_accomplishment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
