# Generated by Django 5.2.6 on 2025-10-04 14:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_family_created_by_familyuser_is_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_family_chats', to='core.family')),
            ],
            options={
                'verbose_name': 'Family Chat',
                'verbose_name_plural': 'Family Chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_messages', to=settings.AUTH_USER_MODEL)),
                ('family_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_chat_messages', to='messenger.familychat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
