# Generated by Django 5.2.6 on 2025-10-12 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_familyinvite_token'),
        ('messenger', '0003_alter_message_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familychat',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='familychat',
            name='family_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='family_family_chats', to='core.family'),
        ),
    ]
